version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: tailwindcss
        update-types: ["version-update:semver-major"]
      - dependency-name: react
        update-types: ["version-update:semver-major"]
      - dependency-name: react-dom
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
      # No plans on upgrading to ESLint 9 and flat config
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint-plugin-react-hooks
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
