// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/agent.proto

// Package gopher.agent.v1 is the control-plane contract between the Gopher
// server (VPS) and the gopher-agent running on each managed origin machine.
//
// The server reaches the agent through the rathole back-channel (VPS dials
// 127.0.0.1:<remote_port> -> tunnel -> agent on 127.0.0.1:4322). The transport
// is cleartext HTTP/2 (gRPC insecure): the tunnel hop is already encrypted by
// rathole's Noise transport, so wrapping gRPC in TLS again would be redundant.
//
// Every RPC requires a per-machine bearer token in the "authorization"
// metadata header ("Bearer <token>"), enforced by a server-side interceptor.

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type VersionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                         // agent build version, e.g. "0.2.0"
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // wire-compat contract; server gates on this
	Unit            string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                                               // managed systemd unit name
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Arch            string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"` // runtime.GOARCH
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *VersionInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *VersionInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *VersionInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type WatchStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired heartbeat interval in seconds. The agent clamps to a sane range;
	// 0 means "use the agent default".
	HeartbeatSeconds uint32 `protobuf:"varint,1,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *WatchStatusRequest) GetHeartbeatSeconds() uint32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

type StatusInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion    uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentUptimeSeconds int64                  `protobuf:"varint,3,opt,name=agent_uptime_seconds,json=agentUptimeSeconds,proto3" json:"agent_uptime_seconds,omitempty"`
	RestartsServed     int64                  `protobuf:"varint,4,opt,name=restarts_served,json=restartsServed,proto3" json:"restarts_served,omitempty"`
	Rathole            *RatholeStatus         `protobuf:"bytes,5,opt,name=rathole,proto3" json:"rathole,omitempty"`
	System             *SystemStatus          `protobuf:"bytes,6,opt,name=system,proto3" json:"system,omitempty"`
	NowUnix            int64                  `protobuf:"varint,7,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"` // server records receipt time; this is the agent's clock
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusInfo) Reset() {
	*x = StatusInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusInfo) ProtoMessage() {}

func (x *StatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusInfo.ProtoReflect.Descriptor instead.
func (*StatusInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StatusInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusInfo) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *StatusInfo) GetAgentUptimeSeconds() int64 {
	if x != nil {
		return x.AgentUptimeSeconds
	}
	return 0
}

func (x *StatusInfo) GetRestartsServed() int64 {
	if x != nil {
		return x.RestartsServed
	}
	return 0
}

func (x *StatusInfo) GetRathole() *RatholeStatus {
	if x != nil {
		return x.Rathole
	}
	return nil
}

func (x *StatusInfo) GetSystem() *SystemStatus {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *StatusInfo) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

type RatholeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`       // "active", "inactive", "failed", ...
	Substate      string                 `protobuf:"bytes,3,opt,name=substate,proto3" json:"substate,omitempty"` // "running", "dead", ...
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatholeStatus) Reset() {
	*x = RatholeStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatholeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatholeStatus) ProtoMessage() {}

func (x *RatholeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatholeStatus.ProtoReflect.Descriptor instead.
func (*RatholeStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RatholeStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RatholeStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RatholeStatus) GetSubstate() string {
	if x != nil {
		return x.Substate
	}
	return ""
}

func (x *RatholeStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type SystemStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoadAvg_1      float64                `protobuf:"fixed64,1,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5      float64                `protobuf:"fixed64,2,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15     float64                `protobuf:"fixed64,3,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	MemTotalKb     uint64                 `protobuf:"varint,4,opt,name=mem_total_kb,json=memTotalKb,proto3" json:"mem_total_kb,omitempty"`
	MemAvailKb     uint64                 `protobuf:"varint,5,opt,name=mem_avail_kb,json=memAvailKb,proto3" json:"mem_avail_kb,omitempty"`
	DiskFreeBytes  uint64                 `protobuf:"varint,6,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,7,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	Hostname       string                 `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Kernel         string                 `protobuf:"bytes,9,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SystemStatus) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *SystemStatus) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *SystemStatus) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *SystemStatus) GetMemTotalKb() uint64 {
	if x != nil {
		return x.MemTotalKb
	}
	return 0
}

func (x *SystemStatus) GetMemAvailKb() uint64 {
	if x != nil {
		return x.MemAvailKb
	}
	return 0
}

func (x *SystemStatus) GetDiskFreeBytes() uint64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *SystemStatus) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *SystemStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemStatus) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type RestartRatholeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRatholeRequest) Reset() {
	*x = RestartRatholeRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRatholeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRatholeRequest) ProtoMessage() {}

func (x *RestartRatholeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRatholeRequest.ProtoReflect.Descriptor instead.
func (*RestartRatholeRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

type RestartRatholeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restarted     bool                   `protobuf:"varint,1,opt,name=restarted,proto3" json:"restarted,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRatholeResponse) Reset() {
	*x = RestartRatholeResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRatholeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRatholeResponse) ProtoMessage() {}

func (x *RestartRatholeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRatholeResponse.ProtoReflect.Descriptor instead.
func (*RestartRatholeResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RestartRatholeResponse) GetRestarted() bool {
	if x != nil {
		return x.Restarted
	}
	return false
}

func (x *RestartRatholeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GetRatholeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatholeConfigRequest) Reset() {
	*x = GetRatholeConfigRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatholeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatholeConfigRequest) ProtoMessage() {}

func (x *GetRatholeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatholeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRatholeConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

// RatholeConfig carries the client.toml body for both the Get reply and the
// Put request.
type RatholeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toml          string                 `protobuf:"bytes,1,opt,name=toml,proto3" json:"toml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatholeConfig) Reset() {
	*x = RatholeConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatholeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatholeConfig) ProtoMessage() {}

func (x *RatholeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatholeConfig.ProtoReflect.Descriptor instead.
func (*RatholeConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RatholeConfig) GetToml() string {
	if x != nil {
		return x.Toml
	}
	return ""
}

type PutRatholeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       bool                   `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRatholeConfigResponse) Reset() {
	*x = PutRatholeConfigResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRatholeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRatholeConfigResponse) ProtoMessage() {}

func (x *PutRatholeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRatholeConfigResponse.ProtoReflect.Descriptor instead.
func (*PutRatholeConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PutRatholeConfigResponse) GetWritten() bool {
	if x != nil {
		return x.Written
	}
	return false
}

func (x *PutRatholeConfigResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type DiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsRequest) Reset() {
	*x = DiagnosticsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsRequest) ProtoMessage() {}

func (x *DiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

type DiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*DiagCheck           `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DiagnosticsResponse) GetChecks() []*DiagCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type DiagCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pass          bool                   `protobuf:"varint,2,opt,name=pass,proto3" json:"pass,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagCheck) Reset() {
	*x = DiagCheck{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagCheck) ProtoMessage() {}

func (x *DiagCheck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagCheck.ProtoReflect.Descriptor instead.
func (*DiagCheck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DiagCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiagCheck) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *DiagCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type UninstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallRequest) Reset() {
	*x = UninstallRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallRequest) ProtoMessage() {}

func (x *UninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallRequest.ProtoReflect.Descriptor instead.
func (*UninstallRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

type UninstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Log           string                 `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallResponse) Reset() {
	*x = UninstallResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallResponse) ProtoMessage() {}

func (x *UninstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallResponse.ProtoReflect.Descriptor instead.
func (*UninstallResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *UninstallResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *UninstallResponse) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *UninstallResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\x13\n" +
	"\x11GetVersionRequest\"\xa1\x01\n" +
	"\vVersionInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"\x12\n" +
	"\x10GetStatusRequest\"A\n" +
	"\x12WatchStatusRequest\x12+\n" +
	"\x11heartbeat_seconds\x18\x01 \x01(\rR\x10heartbeatSeconds\"\xaa\x02\n" +
	"\n" +
	"StatusInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x120\n" +
	"\x14agent_uptime_seconds\x18\x03 \x01(\x03R\x12agentUptimeSeconds\x12'\n" +
	"\x0frestarts_served\x18\x04 \x01(\x03R\x0erestartsServed\x121\n" +
	"\arathole\x18\x05 \x01(\v2\x17.agent.v1.RatholeStatusR\arathole\x12.\n" +
	"\x06system\x18\x06 \x01(\v2\x16.agent.v1.SystemStatusR\x06system\x12\x19\n" +
	"\bnow_unix\x18\a \x01(\x03R\anowUnix\"q\n" +
	"\rRatholeStatus\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\bsubstate\x18\x03 \x01(\tR\bsubstate\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xb4\x02\n" +
	"\fSystemStatus\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x01 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x02 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x03 \x01(\x01R\tloadAvg15\x12 \n" +
	"\fmem_total_kb\x18\x04 \x01(\x04R\n" +
	"memTotalKb\x12 \n" +
	"\fmem_avail_kb\x18\x05 \x01(\x04R\n" +
	"memAvailKb\x12&\n" +
	"\x0fdisk_free_bytes\x18\x06 \x01(\x04R\rdiskFreeBytes\x12(\n" +
	"\x10disk_total_bytes\x18\a \x01(\x04R\x0ediskTotalBytes\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12\x16\n" +
	"\x06kernel\x18\t \x01(\tR\x06kernel\"\x17\n" +
	"\x15RestartRatholeRequest\"N\n" +
	"\x16RestartRatholeResponse\x12\x1c\n" +
	"\trestarted\x18\x01 \x01(\bR\trestarted\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\x19\n" +
	"\x17GetRatholeConfigRequest\"#\n" +
	"\rRatholeConfig\x12\x12\n" +
	"\x04toml\x18\x01 \x01(\tR\x04toml\"J\n" +
	"\x18PutRatholeConfigResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\bR\awritten\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"\x14\n" +
	"\x12DiagnosticsRequest\"B\n" +
	"\x13DiagnosticsResponse\x12+\n" +
	"\x06checks\x18\x01 \x03(\v2\x13.agent.v1.DiagCheckR\x06checks\"K\n" +
	"\tDiagCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04pass\x18\x02 \x01(\bR\x04pass\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x12\n" +
	"\x10UninstallRequest\"U\n" +
	"\x11UninstallResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x10\n" +
	"\x03log\x18\x03 \x01(\tR\x03log2\xdc\x04\n" +
	"\fAgentControl\x12@\n" +
	"\n" +
	"GetVersion\x12\x1b.agent.v1.GetVersionRequest\x1a\x15.agent.v1.VersionInfo\x12=\n" +
	"\tGetStatus\x12\x1a.agent.v1.GetStatusRequest\x1a\x14.agent.v1.StatusInfo\x12C\n" +
	"\vWatchStatus\x12\x1c.agent.v1.WatchStatusRequest\x1a\x14.agent.v1.StatusInfo0\x01\x12S\n" +
	"\x0eRestartRathole\x12\x1f.agent.v1.RestartRatholeRequest\x1a .agent.v1.RestartRatholeResponse\x12N\n" +
	"\x10GetRatholeConfig\x12!.agent.v1.GetRatholeConfigRequest\x1a\x17.agent.v1.RatholeConfig\x12O\n" +
	"\x10PutRatholeConfig\x12\x17.agent.v1.RatholeConfig\x1a\".agent.v1.PutRatholeConfigResponse\x12J\n" +
	"\vDiagnostics\x12\x1c.agent.v1.DiagnosticsRequest\x1a\x1d.agent.v1.DiagnosticsResponse\x12D\n" +
	"\tUninstall\x12\x1a.agent.v1.UninstallRequest\x1a\x1b.agent.v1.UninstallResponseB5Z3github.com/smalex-z/gopher/internal/agentpb;agentpbb\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agent_v1_agent_proto_goTypes = []any{
	(*GetVersionRequest)(nil),        // 0: agent.v1.GetVersionRequest
	(*VersionInfo)(nil),              // 1: agent.v1.VersionInfo
	(*GetStatusRequest)(nil),         // 2: agent.v1.GetStatusRequest
	(*WatchStatusRequest)(nil),       // 3: agent.v1.WatchStatusRequest
	(*StatusInfo)(nil),               // 4: agent.v1.StatusInfo
	(*RatholeStatus)(nil),            // 5: agent.v1.RatholeStatus
	(*SystemStatus)(nil),             // 6: agent.v1.SystemStatus
	(*RestartRatholeRequest)(nil),    // 7: agent.v1.RestartRatholeRequest
	(*RestartRatholeResponse)(nil),   // 8: agent.v1.RestartRatholeResponse
	(*GetRatholeConfigRequest)(nil),  // 9: agent.v1.GetRatholeConfigRequest
	(*RatholeConfig)(nil),            // 10: agent.v1.RatholeConfig
	(*PutRatholeConfigResponse)(nil), // 11: agent.v1.PutRatholeConfigResponse
	(*DiagnosticsRequest)(nil),       // 12: agent.v1.DiagnosticsRequest
	(*DiagnosticsResponse)(nil),      // 13: agent.v1.DiagnosticsResponse
	(*DiagCheck)(nil),                // 14: agent.v1.DiagCheck
	(*UninstallRequest)(nil),         // 15: agent.v1.UninstallRequest
	(*UninstallResponse)(nil),        // 16: agent.v1.UninstallResponse
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.StatusInfo.rathole:type_name -> agent.v1.RatholeStatus
	6,  // 1: agent.v1.StatusInfo.system:type_name -> agent.v1.SystemStatus
	14, // 2: agent.v1.DiagnosticsResponse.checks:type_name -> agent.v1.DiagCheck
	0,  // 3: agent.v1.AgentControl.GetVersion:input_type -> agent.v1.GetVersionRequest
	2,  // 4: agent.v1.AgentControl.GetStatus:input_type -> agent.v1.GetStatusRequest
	3,  // 5: agent.v1.AgentControl.WatchStatus:input_type -> agent.v1.WatchStatusRequest
	7,  // 6: agent.v1.AgentControl.RestartRathole:input_type -> agent.v1.RestartRatholeRequest
	9,  // 7: agent.v1.AgentControl.GetRatholeConfig:input_type -> agent.v1.GetRatholeConfigRequest
	10, // 8: agent.v1.AgentControl.PutRatholeConfig:input_type -> agent.v1.RatholeConfig
	12, // 9: agent.v1.AgentControl.Diagnostics:input_type -> agent.v1.DiagnosticsRequest
	15, // 10: agent.v1.AgentControl.Uninstall:input_type -> agent.v1.UninstallRequest
	1,  // 11: agent.v1.AgentControl.GetVersion:output_type -> agent.v1.VersionInfo
	4,  // 12: agent.v1.AgentControl.GetStatus:output_type -> agent.v1.StatusInfo
	4,  // 13: agent.v1.AgentControl.WatchStatus:output_type -> agent.v1.StatusInfo
	8,  // 14: agent.v1.AgentControl.RestartRathole:output_type -> agent.v1.RestartRatholeResponse
	10, // 15: agent.v1.AgentControl.GetRatholeConfig:output_type -> agent.v1.RatholeConfig
	11, // 16: agent.v1.AgentControl.PutRatholeConfig:output_type -> agent.v1.PutRatholeConfigResponse
	13, // 17: agent.v1.AgentControl.Diagnostics:output_type -> agent.v1.DiagnosticsResponse
	16, // 18: agent.v1.AgentControl.Uninstall:output_type -> agent.v1.UninstallResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
