// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/agent.proto

// Package gopher.agent.v1 is the control-plane contract between the Gopher
// server (VPS) and the gopher-agent running on each managed origin machine.
//
// The server reaches the agent through the rathole back-channel (VPS dials
// 127.0.0.1:<remote_port> -> tunnel -> agent on 127.0.0.1:4322). The transport
// is cleartext HTTP/2 (gRPC insecure): the tunnel hop is already encrypted by
// rathole's Noise transport, so wrapping gRPC in TLS again would be redundant.
//
// Every RPC requires a per-machine bearer token in the "authorization"
// metadata header ("Bearer <token>"), enforced by a server-side interceptor.

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_GetVersion_FullMethodName       = "/agent.v1.AgentControl/GetVersion"
	AgentControl_GetStatus_FullMethodName        = "/agent.v1.AgentControl/GetStatus"
	AgentControl_WatchStatus_FullMethodName      = "/agent.v1.AgentControl/WatchStatus"
	AgentControl_RestartRathole_FullMethodName   = "/agent.v1.AgentControl/RestartRathole"
	AgentControl_GetRatholeConfig_FullMethodName = "/agent.v1.AgentControl/GetRatholeConfig"
	AgentControl_PutRatholeConfig_FullMethodName = "/agent.v1.AgentControl/PutRatholeConfig"
	AgentControl_Diagnostics_FullMethodName      = "/agent.v1.AgentControl/Diagnostics"
	AgentControl_Uninstall_FullMethodName        = "/agent.v1.AgentControl/Uninstall"
	AgentControl_GetNetworkInfo_FullMethodName   = "/agent.v1.AgentControl/GetNetworkInfo"
	AgentControl_SetManagedKey_FullMethodName    = "/agent.v1.AgentControl/SetManagedKey"
	AgentControl_CheckPorts_FullMethodName       = "/agent.v1.AgentControl/CheckPorts"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControl is the full set of control operations the VPS performs against
// an origin's agent. It replaces the previous HTTP/JSON API one-for-one and
// adds WatchStatus for push-based health.
type AgentControlClient interface {
	// GetVersion reports the agent build version and the wire protocol version.
	// The server gates compatibility on protocol_version, not the semver string.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionInfo, error)
	// GetStatus returns a one-shot system + rathole status snapshot.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusInfo, error)
	// WatchStatus streams status snapshots: one immediately, then on change and
	// on a periodic heartbeat. The stream dropping is itself the signal that the
	// agent/origin is gone — this is what lets the server detect death without
	// polling.
	WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusInfo], error)
	// RestartRathole runs `systemctl start rathole-client` (start, never
	// restart — start resurrects a stopped/failed unit without dropping the
	// active tunnels a restart would kill).
	RestartRathole(ctx context.Context, in *RestartRatholeRequest, opts ...grpc.CallOption) (*RestartRatholeResponse, error)
	// GetRatholeConfig returns the current /etc/rathole/client.toml.
	GetRatholeConfig(ctx context.Context, in *GetRatholeConfigRequest, opts ...grpc.CallOption) (*RatholeConfig, error)
	// PutRatholeConfig writes a new client.toml in place; rathole's notify
	// watcher reloads it via inotify without a restart.
	PutRatholeConfig(ctx context.Context, in *RatholeConfig, opts ...grpc.CallOption) (*PutRatholeConfigResponse, error)
	// Diagnostics runs structured pass/fail checks on the origin.
	Diagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
	// Uninstall kicks off a detached worker that runs the on-disk
	// gopher-uninstall script and returns immediately.
	Uninstall(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*UninstallResponse, error)
	// GetNetworkInfo discovers the origin's WAN (public) and LAN (private) IPs
	// on demand — kept out of the periodic status snapshot because the WAN
	// lookup makes an outbound network call. Lets the server show network-map
	// info without SSHing into the origin. (Added in agent 0.2.2; older agents
	// return Unimplemented and the server falls back to SSH.)
	GetNetworkInfo(ctx context.Context, in *GetNetworkInfoRequest, opts ...grpc.CallOption) (*NetworkInfo, error)
	// SetManagedKey makes public_key the ONE gopher-managed key in a user's
	// authorized_keys: it removes every prior gopher-managed key (tagged with the
	// `gopher-managed` comment) and adds this one. Operator-owned keys are never
	// touched. Lets key rotation happen without the server holding an SSH private
	// key, and keeps authorized_keys from accumulating stale keys. (Added in agent
	// 0.2.2; older agents return Unimplemented.)
	SetManagedKey(ctx context.Context, in *SetManagedKeyRequest, opts ...grpc.CallOption) (*SetManagedKeyResponse, error)
	// CheckPorts reports whether the origin is bound/listening on the given local
	// ports (tcp/udp), read from /proc/net. This is the definitive idle-vs-serving
	// signal the server cannot get by probing the rathole port from the edge —
	// impossible for UDP (connectionless), and only heuristic for TCP. (Added in
	// agent 0.2.3; older agents return Unimplemented and the server falls back to
	// the edge probe.)
	CheckPorts(ctx context.Context, in *CheckPortsRequest, opts ...grpc.CallOption) (*CheckPortsResponse, error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, AgentControl_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusInfo)
	err := c.cc.Invoke(ctx, AgentControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_WatchStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStatusRequest, StatusInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_WatchStatusClient = grpc.ServerStreamingClient[StatusInfo]

func (c *agentControlClient) RestartRathole(ctx context.Context, in *RestartRatholeRequest, opts ...grpc.CallOption) (*RestartRatholeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartRatholeResponse)
	err := c.cc.Invoke(ctx, AgentControl_RestartRathole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetRatholeConfig(ctx context.Context, in *GetRatholeConfigRequest, opts ...grpc.CallOption) (*RatholeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatholeConfig)
	err := c.cc.Invoke(ctx, AgentControl_GetRatholeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) PutRatholeConfig(ctx context.Context, in *RatholeConfig, opts ...grpc.CallOption) (*PutRatholeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutRatholeConfigResponse)
	err := c.cc.Invoke(ctx, AgentControl_PutRatholeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Diagnostics(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, AgentControl_Diagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Uninstall(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*UninstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallResponse)
	err := c.cc.Invoke(ctx, AgentControl_Uninstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetNetworkInfo(ctx context.Context, in *GetNetworkInfoRequest, opts ...grpc.CallOption) (*NetworkInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInfo)
	err := c.cc.Invoke(ctx, AgentControl_GetNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) SetManagedKey(ctx context.Context, in *SetManagedKeyRequest, opts ...grpc.CallOption) (*SetManagedKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetManagedKeyResponse)
	err := c.cc.Invoke(ctx, AgentControl_SetManagedKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) CheckPorts(ctx context.Context, in *CheckPortsRequest, opts ...grpc.CallOption) (*CheckPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPortsResponse)
	err := c.cc.Invoke(ctx, AgentControl_CheckPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
//
// AgentControl is the full set of control operations the VPS performs against
// an origin's agent. It replaces the previous HTTP/JSON API one-for-one and
// adds WatchStatus for push-based health.
type AgentControlServer interface {
	// GetVersion reports the agent build version and the wire protocol version.
	// The server gates compatibility on protocol_version, not the semver string.
	GetVersion(context.Context, *GetVersionRequest) (*VersionInfo, error)
	// GetStatus returns a one-shot system + rathole status snapshot.
	GetStatus(context.Context, *GetStatusRequest) (*StatusInfo, error)
	// WatchStatus streams status snapshots: one immediately, then on change and
	// on a periodic heartbeat. The stream dropping is itself the signal that the
	// agent/origin is gone — this is what lets the server detect death without
	// polling.
	WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusInfo]) error
	// RestartRathole runs `systemctl start rathole-client` (start, never
	// restart — start resurrects a stopped/failed unit without dropping the
	// active tunnels a restart would kill).
	RestartRathole(context.Context, *RestartRatholeRequest) (*RestartRatholeResponse, error)
	// GetRatholeConfig returns the current /etc/rathole/client.toml.
	GetRatholeConfig(context.Context, *GetRatholeConfigRequest) (*RatholeConfig, error)
	// PutRatholeConfig writes a new client.toml in place; rathole's notify
	// watcher reloads it via inotify without a restart.
	PutRatholeConfig(context.Context, *RatholeConfig) (*PutRatholeConfigResponse, error)
	// Diagnostics runs structured pass/fail checks on the origin.
	Diagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
	// Uninstall kicks off a detached worker that runs the on-disk
	// gopher-uninstall script and returns immediately.
	Uninstall(context.Context, *UninstallRequest) (*UninstallResponse, error)
	// GetNetworkInfo discovers the origin's WAN (public) and LAN (private) IPs
	// on demand — kept out of the periodic status snapshot because the WAN
	// lookup makes an outbound network call. Lets the server show network-map
	// info without SSHing into the origin. (Added in agent 0.2.2; older agents
	// return Unimplemented and the server falls back to SSH.)
	GetNetworkInfo(context.Context, *GetNetworkInfoRequest) (*NetworkInfo, error)
	// SetManagedKey makes public_key the ONE gopher-managed key in a user's
	// authorized_keys: it removes every prior gopher-managed key (tagged with the
	// `gopher-managed` comment) and adds this one. Operator-owned keys are never
	// touched. Lets key rotation happen without the server holding an SSH private
	// key, and keeps authorized_keys from accumulating stale keys. (Added in agent
	// 0.2.2; older agents return Unimplemented.)
	SetManagedKey(context.Context, *SetManagedKeyRequest) (*SetManagedKeyResponse, error)
	// CheckPorts reports whether the origin is bound/listening on the given local
	// ports (tcp/udp), read from /proc/net. This is the definitive idle-vs-serving
	// signal the server cannot get by probing the rathole port from the edge —
	// impossible for UDP (connectionless), and only heuristic for TCP. (Added in
	// agent 0.2.3; older agents return Unimplemented and the server falls back to
	// the edge probe.)
	CheckPorts(context.Context, *CheckPortsRequest) (*CheckPortsResponse, error)
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) GetVersion(context.Context, *GetVersionRequest) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedAgentControlServer) GetStatus(context.Context, *GetStatusRequest) (*StatusInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentControlServer) WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusInfo]) error {
	return status.Error(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedAgentControlServer) RestartRathole(context.Context, *RestartRatholeRequest) (*RestartRatholeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartRathole not implemented")
}
func (UnimplementedAgentControlServer) GetRatholeConfig(context.Context, *GetRatholeConfigRequest) (*RatholeConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRatholeConfig not implemented")
}
func (UnimplementedAgentControlServer) PutRatholeConfig(context.Context, *RatholeConfig) (*PutRatholeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutRatholeConfig not implemented")
}
func (UnimplementedAgentControlServer) Diagnostics(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diagnostics not implemented")
}
func (UnimplementedAgentControlServer) Uninstall(context.Context, *UninstallRequest) (*UninstallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Uninstall not implemented")
}
func (UnimplementedAgentControlServer) GetNetworkInfo(context.Context, *GetNetworkInfoRequest) (*NetworkInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkInfo not implemented")
}
func (UnimplementedAgentControlServer) SetManagedKey(context.Context, *SetManagedKeyRequest) (*SetManagedKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetManagedKey not implemented")
}
func (UnimplementedAgentControlServer) CheckPorts(context.Context, *CheckPortsRequest) (*CheckPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPorts not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).WatchStatus(m, &grpc.GenericServerStream[WatchStatusRequest, StatusInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_WatchStatusServer = grpc.ServerStreamingServer[StatusInfo]

func _AgentControl_RestartRathole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRatholeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).RestartRathole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_RestartRathole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).RestartRathole(ctx, req.(*RestartRatholeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetRatholeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatholeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetRatholeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetRatholeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetRatholeConfig(ctx, req.(*GetRatholeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_PutRatholeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatholeConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).PutRatholeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_PutRatholeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).PutRatholeConfig(ctx, req.(*RatholeConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Diagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Diagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Diagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Diagnostics(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Uninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Uninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Uninstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Uninstall(ctx, req.(*UninstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetNetworkInfo(ctx, req.(*GetNetworkInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_SetManagedKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetManagedKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).SetManagedKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_SetManagedKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).SetManagedKey(ctx, req.(*SetManagedKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_CheckPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).CheckPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_CheckPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).CheckPorts(ctx, req.(*CheckPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AgentControl_GetVersion_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AgentControl_GetStatus_Handler,
		},
		{
			MethodName: "RestartRathole",
			Handler:    _AgentControl_RestartRathole_Handler,
		},
		{
			MethodName: "GetRatholeConfig",
			Handler:    _AgentControl_GetRatholeConfig_Handler,
		},
		{
			MethodName: "PutRatholeConfig",
			Handler:    _AgentControl_PutRatholeConfig_Handler,
		},
		{
			MethodName: "Diagnostics",
			Handler:    _AgentControl_Diagnostics_Handler,
		},
		{
			MethodName: "Uninstall",
			Handler:    _AgentControl_Uninstall_Handler,
		},
		{
			MethodName: "GetNetworkInfo",
			Handler:    _AgentControl_GetNetworkInfo_Handler,
		},
		{
			MethodName: "SetManagedKey",
			Handler:    _AgentControl_SetManagedKey_Handler,
		},
		{
			MethodName: "CheckPorts",
			Handler:    _AgentControl_CheckPorts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _AgentControl_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
