[sshd]
enabled = true
mode    = aggressive

[gopher-auth]
enabled  = true
filter   = gopher-auth
backend  = systemd
journalmatch = _SYSTEMD_UNIT=gopher.service
maxretry = 5
findtime = 300
bantime  = 3600
action   = iptables-allports[name=gopher, protocol=all]

[rathole-auth]
enabled  = true
filter   = rathole-auth
backend  = systemd
journalmatch = _SYSTEMD_UNIT=rathole-server.service
maxretry = 30
findtime = 600
bantime  = 86400
action   = iptables-allports[name=rathole, protocol=all]
