[sshd]
enabled = true
mode    = aggressive

[gopher-auth]
enabled  = true
filter   = gopher-auth
backend  = systemd
journalmatch = _SYSTEMD_UNIT=gopher.service
maxretry = 5
findtime = 300
bantime  = 3600
action   = iptables-allports[name=gopher, protocol=all]
